Check that stable deployments are running from same commit as build

diff --git a/.github/workflows/deploy-pudl.yml b/.github/workflows/deploy-pudl.yml
--- a/.github/workflows/deploy-pudl.yml
+++ b/.github/workflows/deploy-pudl.yml
@@ -59,6 +59,13 @@ jobs:
             exit 1
           fi
 
+          TAG_SHA=$(git rev-list -n 1 "$TAG")
+          CURRENT_SHA="${{ github.sha }}"
+          if [[ "$CURRENT_SHA" != "$TAG_SHA" ]] && [[ "$TAG" == v* ]]; then
+            echo "::error::Stable deployments must be run from the same commit that produced the build!"
+            exit 1
+          fi
+
       - name: Docker Metadata
         id: docker_metadata
         uses: docker/metadata-action@v5
